### ISSUE TITLE
Unhandled exception when I try to close connection.

### ISSUE THREAD

**Issue by ghost** [MicroMinion/turn-js#6] opened 2016-04-26 10:34 UTC
Hello, when I try to close turn connection I got an Unhandled exception:

Error: client error: Error: read ECONNRESET
    at Socket.<anonymous> (/home/mihael/Projects/cloud-compute/node_modules/turn-js/node_modules/stun-js/src/stun_comm.js:146:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)

**Comment by nicojanssens** [comment] 2016-04-26 17:58
Hi @iMihael,

I didn't face this error so far while testing this module against my own TURN servers. So I'd like to  reproduce that error first, for which I need some additional info about your setup.

Does this error also occur if you run my example scripts?

Are you running your own TURN server? If so, can you create me a test account to reproduce this error?

**Comment by ghost** [comment] 2016-04-26 21:34
I'm running own turnserver **coturn** https://github.com/coturn/coturn
test account:
host: cloudcompute.tk
port: 19312
username: test
password: test

Yout test script works fine. It's strange, maybe my code is bad. Code:
client.close(function () {}, function (error) {
             console.log(error);
        });

**Comment by nicojanssens** [comment] 2016-04-28 19:11
@iMihael: I added some extra catch statements to my tests and my examples, but was not able to reproduce this issue. I also used your coturn server + ran my scripts using both TCP and UDP transports, and all seems to work fine.

**Comment by nicojanssens** [comment] 2016-06-07 10:21
ECONNRESET errors should be fixed in latest version.

**Closed as completed by nicojanssens** 2016-06-07 10:21 UTC
